


2020-08-18-11:11:41    START: Starting API...
2020-08-18-11:11:41    INFO: Calling: create_app...
2020-08-18-11:11:51    INFO: Calling: receive_data...
2020-08-18-11:11:51    INFO: Route '/api/upload' was called...
2020-08-18-11:11:51    INFO: Storing query in data directory...
2020-08-18-11:11:51    INFO: Dummy processing...
2020-08-18-11:11:51    INFO: Encoding result and returning response...
2020-08-18-11:11:55    INFO: Calling: receive_data...
2020-08-18-11:11:55    INFO: Route '/api/upload' was called...
2020-08-18-11:11:55    INFO: Storing query in data directory...
2020-08-18-11:11:55    INFO: Dummy processing...
2020-08-18-11:11:55    INFO: Encoding result and returning response...
2020-08-18-11:11:56    INFO: Calling: receive_data...
2020-08-18-11:11:56    INFO: Route '/api/upload' was called...
2020-08-18-11:11:56    INFO: Storing query in data directory...
2020-08-18-11:11:56    INFO: Dummy processing...
2020-08-18-11:11:56    INFO: Encoding result and returning response...
2020-08-18-11:11:57    INFO: Calling: receive_data...
2020-08-18-11:11:57    INFO: Route '/api/upload' was called...
2020-08-18-11:11:57    INFO: Storing query in data directory...
2020-08-18-11:11:57    INFO: Dummy processing...
2020-08-18-11:11:57    INFO: Encoding result and returning response...
2020-08-18-11:11:58    INFO: Calling: receive_data...
2020-08-18-11:11:58    INFO: Route '/api/upload' was called...
2020-08-18-11:11:58    INFO: Storing query in data directory...
2020-08-18-11:11:58    INFO: Dummy processing...
2020-08-18-11:11:58    INFO: Encoding result and returning response...
2020-08-18-11:11:58    INFO: Calling: receive_data...
2020-08-18-11:11:58    INFO: Route '/api/upload' was called...
2020-08-18-11:11:58    INFO: Storing query in data directory...
2020-08-18-11:11:58    INFO: Dummy processing...
2020-08-18-11:11:58    INFO: Encoding result and returning response...
2020-08-18-12:45:21    INFO: Calling: receive_data...
2020-08-18-12:45:21    INFO: Route '/api/upload' was called...
2020-08-18-12:45:21    INFO: Storing query in data directory...
2020-08-18-12:45:21    INFO: Dummy processing...
2020-08-18-12:45:21    INFO: Encoding result and returning response...
2020-08-18-12:45:22    INFO: Calling: receive_data...
2020-08-18-12:45:22    INFO: Route '/api/upload' was called...
2020-08-18-12:45:22    INFO: Storing query in data directory...
2020-08-18-12:45:22    INFO: Dummy processing...
2020-08-18-12:45:23    INFO: Encoding result and returning response...
2020-08-18-12:45:24    INFO: Calling: receive_data...
2020-08-18-12:45:24    INFO: Route '/api/upload' was called...
2020-08-18-12:45:24    INFO: Storing query in data directory...
2020-08-18-12:45:24    INFO: Dummy processing...
2020-08-18-12:45:25    INFO: Encoding result and returning response...



2020-08-20-09:50:50    START: Starting API...
2020-08-20-09:50:50    INFO: Calling: create_app...
2020-08-20-09:51:08    INFO: Calling: receive_data...
2020-08-20-09:51:08    INFO: Route '/api/upload' was called...
2020-08-20-09:51:08    INFO: Storing query in data directory...
2020-08-20-09:51:08    INFO: Dummy processing...
2020-08-20-09:51:08    INFO: Encoding result and returning response...
2020-08-20-09:51:10    INFO: Calling: receive_data...
2020-08-20-09:51:10    INFO: Route '/api/upload' was called...
2020-08-20-09:51:10    INFO: Storing query in data directory...
2020-08-20-09:51:10    INFO: Dummy processing...
2020-08-20-09:51:10    INFO: Encoding result and returning response...
2020-08-20-09:51:11    INFO: Calling: receive_data...
2020-08-20-09:51:11    INFO: Route '/api/upload' was called...
2020-08-20-09:51:11    INFO: Storing query in data directory...
2020-08-20-09:51:11    INFO: Dummy processing...
2020-08-20-09:51:11    INFO: Encoding result and returning response...
2020-08-20-09:54:12    INFO: Calling: receive_data...
2020-08-20-09:54:12    INFO: Route '/api/upload' was called...
2020-08-20-09:54:12    INFO: Storing query in data directory...
2020-08-20-09:54:12    ERROR: Traceback (most recent call last):
  File "/home/angel/Dropbox/Angel Villar Corrales/Telecos/8-Fourth Master Semester/MasterThesis/RetrievalDemo/src/API/lib/logger.py", line 26, in try_call_log
    return func(*args, **kwargs)
  File "/home/angel/Dropbox/Angel Villar Corrales/Telecos/8-Fourth Master Semester/MasterThesis/RetrievalDemo/src/API/routes/upload.py", line 56, in receive_data
    storage_element = files["file"]
  File "/home/angel/miniconda3/lib/python3.7/site-packages/werkzeug/datastructures.py", line 442, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.HTTPException.wrap.<locals>.newcls: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.




2020-08-20-09:54:40    START: Starting API...
2020-08-20-09:54:40    INFO: Calling: create_app...
2020-08-20-09:54:43    INFO: Calling: receive_data...
2020-08-20-09:54:43    INFO: Route '/api/upload' was called...
2020-08-20-09:54:43    INFO: Storing query in data directory...
2020-08-20-09:54:43    ERROR: Traceback (most recent call last):
  File "/home/angel/Dropbox/Angel Villar Corrales/Telecos/8-Fourth Master Semester/MasterThesis/RetrievalDemo/src/API/lib/logger.py", line 26, in try_call_log
    return func(*args, **kwargs)
  File "/home/angel/Dropbox/Angel Villar Corrales/Telecos/8-Fourth Master Semester/MasterThesis/RetrievalDemo/src/API/routes/upload.py", line 56, in receive_data
    storage_element = files["file"]
  File "/home/angel/miniconda3/lib/python3.7/site-packages/werkzeug/datastructures.py", line 442, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.HTTPException.wrap.<locals>.newcls: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.




2020-08-20-10:00:31    START: Starting API...
2020-08-20-10:00:31    INFO: Calling: create_app...
2020-08-20-10:00:34    INFO: Calling: receive_data...
2020-08-20-10:00:34    INFO: Route '/api/upload' was called...
2020-08-20-10:00:34    INFO: Storing query in data directory...
2020-08-20-10:00:34    INFO: Dummy processing...
2020-08-20-10:00:34    INFO: Encoding result and returning response...
2020-08-20-10:00:40    INFO: Calling: receive_data...
2020-08-20-10:00:40    INFO: Route '/api/upload' was called...
2020-08-20-10:00:40    INFO: Storing query in data directory...
2020-08-20-10:00:40    INFO: Dummy processing...
2020-08-20-10:00:41    ERROR: Traceback (most recent call last):
  File "/home/angel/Dropbox/Angel Villar Corrales/Telecos/8-Fourth Master Semester/MasterThesis/RetrievalDemo/src/API/lib/logger.py", line 26, in try_call_log
    return func(*args, **kwargs)
  File "/home/angel/Dropbox/Angel Villar Corrales/Telecos/8-Fourth Master Semester/MasterThesis/RetrievalDemo/src/API/routes/upload.py", line 73, in receive_data
    cv2.imwrite(final_path, img)
cv2.error: OpenCV(4.1.0) /io/opencv/modules/imgcodecs/src/loadsave.cpp:662: error: (-2:Unspecified error) could not find a writer for the specified extension in function 'imwrite_'


2020-08-20-10:07:18    INFO: Calling: receive_data...
2020-08-20-10:07:18    INFO: Route '/api/upload' was called...
2020-08-20-10:07:18    INFO: Storing query in data directory...
2020-08-20-10:07:18    INFO: Dummy processing...
2020-08-20-10:07:18    INFO: Encoding result and returning response...



2020-08-20-10:08:24    START: Starting API...
2020-08-20-10:08:24    INFO: Calling: create_app...
2020-08-20-10:08:29    INFO: Calling: receive_data...
2020-08-20-10:08:29    INFO: Route '/api/upload' was called...
2020-08-20-10:08:29    INFO: Storing query in data directory...
2020-08-20-10:08:29    INFO: Dummy processing...
2020-08-20-10:08:29    INFO: Encoding result and returning response...
2020-08-20-10:08:31    INFO: Calling: receive_data...
2020-08-20-10:08:31    INFO: Route '/api/upload' was called...
2020-08-20-10:08:32    INFO: Storing query in data directory...
2020-08-20-10:08:32    INFO: Dummy processing...
2020-08-20-10:08:32    INFO: Encoding result and returning response...
2020-08-20-10:09:47    INFO: Calling: receive_data...
2020-08-20-10:09:47    INFO: Route '/api/upload' was called...
2020-08-20-10:09:48    INFO: Storing query in data directory...
2020-08-20-10:09:48    INFO: Dummy processing...
2020-08-20-10:09:48    INFO: Encoding result and returning response...



2020-08-20-10:10:23    START: Starting API...
2020-08-20-10:10:23    INFO: Calling: create_app...
2020-08-20-10:10:29    INFO: Calling: receive_data...
2020-08-20-10:10:29    INFO: Route '/api/upload' was called...
2020-08-20-10:10:29    INFO: Storing query in data directory...
2020-08-20-10:10:29    INFO: Calling: setup_detector...
2020-08-20-10:10:29    INFO: Initializing Person Detector
2020-08-20-10:10:33    INFO: Loading detector pretrained parameters 
2020-08-20-10:10:40    INFO: Calling: person_detection...
2020-08-20-10:10:40    INFO: torch.Size([1, 3, 2511, 3806])
2020-08-20-10:10:40    INFO: Computing forward pass through person detector
2020-08-20-10:10:41    ERROR: Traceback (most recent call last):
  File "/home/angel/Dropbox/Angel Villar Corrales/Telecos/8-Fourth Master Semester/MasterThesis/RetrievalDemo/src/API/lib/logger.py", line 26, in try_call_log
    return func(*args, **kwargs)
  File "/home/angel/Dropbox/Angel Villar Corrales/Telecos/8-Fourth Master Semester/MasterThesis/RetrievalDemo/src/API/lib/person_detection.py", line 57, in person_detection
    outputs = model(img / 255)
  File "/home/angel/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/angel/miniconda3/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 140, in forward
    return self.module(*inputs, **kwargs)
  File "/home/angel/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/angel/miniconda3/lib/python3.7/site-packages/torchvision/models/detection/generalized_rcnn.py", line 47, in forward
    images, targets = self.transform(images, targets)
  File "/home/angel/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/angel/miniconda3/lib/python3.7/site-packages/torchvision/models/detection/transform.py", line 41, in forward
    images[i] = image
RuntimeError: The expanded size of the tensor (3806) must match the existing size (1212) at non-singleton dimension 2.  Target sizes: [3, 2511, 3806].  Tensor sizes: [3, 800, 1212]

2020-08-20-10:10:41    INFO: Dummy processing...
2020-08-20-10:10:41    INFO: Encoding result and returning response...



2020-08-20-10:14:37    START: Starting API...
2020-08-20-10:14:37    INFO: Calling: create_app...
2020-08-20-10:14:41    INFO: Calling: receive_data...
2020-08-20-10:14:41    INFO: Route '/api/upload' was called...
2020-08-20-10:14:41    INFO: Storing query in data directory...
2020-08-20-10:14:42    INFO: Calling: setup_detector...
2020-08-20-10:14:42    INFO: Initializing Person Detector
2020-08-20-10:14:45    INFO: Calling: person_detection...
2020-08-20-10:14:45    INFO: torch.Size([1, 3, 2511, 3806])
2020-08-20-10:14:45    INFO: Computing forward pass through person detector
2020-08-20-10:14:46    ERROR: Traceback (most recent call last):
  File "/home/angel/Dropbox/Angel Villar Corrales/Telecos/8-Fourth Master Semester/MasterThesis/RetrievalDemo/src/API/lib/logger.py", line 26, in try_call_log
    return func(*args, **kwargs)
  File "/home/angel/Dropbox/Angel Villar Corrales/Telecos/8-Fourth Master Semester/MasterThesis/RetrievalDemo/src/API/lib/person_detection.py", line 57, in person_detection
    outputs = model(img / 255)
  File "/home/angel/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/angel/miniconda3/lib/python3.7/site-packages/torchvision/models/detection/generalized_rcnn.py", line 47, in forward
    images, targets = self.transform(images, targets)
  File "/home/angel/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/angel/miniconda3/lib/python3.7/site-packages/torchvision/models/detection/transform.py", line 41, in forward
    images[i] = image
RuntimeError: The expanded size of the tensor (3806) must match the existing size (1212) at non-singleton dimension 2.  Target sizes: [3, 2511, 3806].  Tensor sizes: [3, 800, 1212]

2020-08-20-10:14:46    INFO: Dummy processing...
2020-08-20-10:14:46    INFO: Encoding result and returning response...



2020-08-20-10:16:45    START: Starting API...
2020-08-20-10:16:45    INFO: Calling: create_app...
2020-08-20-10:16:47    INFO: Calling: receive_data...
2020-08-20-10:16:47    INFO: Route '/api/upload' was called...
2020-08-20-10:16:47    INFO: Storing query in data directory...
2020-08-20-10:16:48    INFO: Calling: setup_detector...
2020-08-20-10:16:48    INFO: Initializing Person Detector
2020-08-20-10:16:48    INFO: Calling: person_detection...
2020-08-20-10:16:48    INFO: torch.Size([1, 3, 2511, 3806])
2020-08-20-10:16:48    INFO: Computing forward pass through person detector
2020-08-20-10:16:49    ERROR: Traceback (most recent call last):
  File "/home/angel/Dropbox/Angel Villar Corrales/Telecos/8-Fourth Master Semester/MasterThesis/RetrievalDemo/src/API/lib/logger.py", line 26, in try_call_log
    return func(*args, **kwargs)
  File "/home/angel/Dropbox/Angel Villar Corrales/Telecos/8-Fourth Master Semester/MasterThesis/RetrievalDemo/src/API/lib/person_detection.py", line 57, in person_detection
    outputs = model(img / 255)
  File "/home/angel/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/angel/miniconda3/lib/python3.7/site-packages/torchvision/models/detection/generalized_rcnn.py", line 47, in forward
    images, targets = self.transform(images, targets)
  File "/home/angel/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/angel/miniconda3/lib/python3.7/site-packages/torchvision/models/detection/transform.py", line 41, in forward
    images[i] = image
RuntimeError: The expanded size of the tensor (3806) must match the existing size (1212) at non-singleton dimension 2.  Target sizes: [3, 2511, 3806].  Tensor sizes: [3, 800, 1212]

2020-08-20-10:16:49    INFO: Dummy processing...
2020-08-20-10:16:49    INFO: Encoding result and returning response...



2020-08-20-10:16:58    START: Starting API...
2020-08-20-10:16:58    INFO: Calling: create_app...
2020-08-20-10:17:04    INFO: Calling: receive_data...
2020-08-20-10:17:04    INFO: Route '/api/upload' was called...
2020-08-20-10:17:04    INFO: Storing query in data directory...
2020-08-20-10:17:04    INFO: Calling: setup_detector...
2020-08-20-10:17:04    INFO: Initializing Person Detector
2020-08-20-10:17:04    INFO: Calling: person_detection...
2020-08-20-10:17:04    INFO: torch.Size([1, 3, 1694, 1271])
2020-08-20-10:17:04    INFO: Computing forward pass through person detector
2020-08-20-10:17:04    ERROR: Traceback (most recent call last):
  File "/home/angel/Dropbox/Angel Villar Corrales/Telecos/8-Fourth Master Semester/MasterThesis/RetrievalDemo/src/API/lib/logger.py", line 26, in try_call_log
    return func(*args, **kwargs)
  File "/home/angel/Dropbox/Angel Villar Corrales/Telecos/8-Fourth Master Semester/MasterThesis/RetrievalDemo/src/API/lib/person_detection.py", line 57, in person_detection
    outputs = model(img / 255)
  File "/home/angel/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/angel/miniconda3/lib/python3.7/site-packages/torchvision/models/detection/generalized_rcnn.py", line 47, in forward
    images, targets = self.transform(images, targets)
  File "/home/angel/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/angel/miniconda3/lib/python3.7/site-packages/torchvision/models/detection/transform.py", line 41, in forward
    images[i] = image
RuntimeError: The expanded size of the tensor (1271) must match the existing size (800) at non-singleton dimension 2.  Target sizes: [3, 1694, 1271].  Tensor sizes: [3, 1066, 800]

2020-08-20-10:17:04    INFO: Dummy processing...
2020-08-20-10:17:05    INFO: Encoding result and returning response...
